# Generated by Django 5.2.3 on 2025-07-03 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori Utama')),
            ],
            options={
                'verbose_name_plural': '1. Kategori Alat',
            },
        ),
        migrations.CreateModel(
            name='Laboratorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_ruang', models.CharField(max_length=20, unique=True, verbose_name='Kode Ruang Lab')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='lab_images/')),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi tentang laboratorium', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nip', models.CharField(max_length=50, unique=True, verbose_name='NIP')),
                ('foto', models.ImageField(upload_to='foto_plp/')),
            ],
        ),
        migrations.CreateModel(
            name='KategoriAlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Raspberry Pi, Proyektor, Mouse', max_length=100, unique=True)),
                ('kategori_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_kategori', to='laboratorium.kategoriutama')),
            ],
            options={
                'verbose_name_plural': '2. Jenis Alat',
            },
        ),
        migrations.CreateModel(
            name='JadwalLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_jadwal', models.ImageField(upload_to='jadwal_lab/')),
                ('keterangan', models.CharField(blank=True, help_text='Contoh: Jadwal Praktikum Ganjil 2025', max_length=255, null=True)),
                ('laboratorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='laboratorium.laboratorium')),
            ],
            options={
                'verbose_name_plural': 'Jadwal Lab',
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alat_baru', models.BooleanField(default=False, verbose_name='Apakah ini alat baru?')),
                ('nama_alat_baru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Alat Baru')),
                ('tipe_alat_baru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipe/Merk Alat Baru')),
                ('sn_alat_baru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number (Opsional)')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('status_peminjam', models.CharField(choices=[('Mahasiswa', 'Mahasiswa'), ('Dosen', 'Dosen'), ('Karyawan', 'Karyawan')], max_length=20)),
                ('nrp_nip', models.CharField(max_length=30, verbose_name='NRP/NIP')),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('dosen_perkuliahan', models.CharField(max_length=150)),
                ('nama_plp', models.CharField(max_length=150)),
                ('catatan_kondisi', models.TextField(help_text='Isi dengan kondisi barang saat Anda pinjam (contoh: ada goresan kecil di bodi)', verbose_name='Catatan Kondisi Barang Saat Dipinjam')),
                ('status_peminjaman', models.CharField(choices=[('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak'), ('Dikembalikan', 'Dikembalikan')], default='Menunggu Persetujuan', max_length=30)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('kondisi_saat_kembali', models.CharField(blank=True, choices=[('Baik', 'Baik'), ('Perlu Perbaikan', 'Perlu Perbaikan'), ('Rusak', 'Rusak')], max_length=20, null=True)),
                ('tanggal_pinjam', models.DateTimeField(auto_now_add=True)),
                ('laboratorium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorium.laboratorium')),
                ('peminjam', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data Peminjaman',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengembali', models.CharField(default='', max_length=150, verbose_name='Nama Lengkap Pengembali')),
                ('bukti_peminjaman', models.FileField(blank=True, null=True, upload_to='bukti_kembali/', verbose_name='Upload Bukti Peminjaman (Opsional)')),
                ('tanggal_pengembalian', models.DateField(auto_now_add=True)),
                ('kondisi_barang', models.CharField(choices=[('Baik', 'Baik'), ('Rusak', 'Rusak'), ('Minus', 'Minus')], max_length=20)),
                ('status', models.CharField(choices=[('Menunggu Konfirmasi', 'Menunggu Konfirmasi'), ('Diterima', 'Diterima')], default='Menunggu Konfirmasi', max_length=30)),
                ('nama_plp', models.CharField(help_text='Isi dengan nama PLP yang menerima barang', max_length=150)),
                ('peminjaman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratorium.peminjaman')),
            ],
            options={
                'verbose_name_plural': 'Data Pengembalian',
                'ordering': ['-tanggal_pengembalian'],
            },
        ),
        migrations.AddField(
            model_name='laboratorium',
            name='plp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorium.plp', verbose_name='PLP Penanggung Jawab'),
        ),
        migrations.CreateModel(
            name='UnitAlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_atau_merk', models.CharField(help_text='Contoh: Raspberry Pi 4 Model B', max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('tahun_perolehan', models.PositiveIntegerField(help_text='Tahun alat ini dibeli/diterima')),
                ('kondisi', models.CharField(choices=[('Baik', 'Baik'), ('Perlu Perbaikan', 'Perlu Perbaikan'), ('Rusak', 'Rusak')], default='Baik', max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_alat/', verbose_name='Foto Alat')),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Dipinjam', 'Dipinjam')], default='Tersedia', max_length=100)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_alat', to='laboratorium.kategorialat')),
            ],
            options={
                'verbose_name_plural': '3. Unit Alat',
                'ordering': ['kategori', 'tipe_atau_merk'],
            },
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='unit_alat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='laboratorium.unitalat'),
        ),
    ]
